import { PositionItem } from './types';

export const INITIAL_POSITIONS: PositionItem[] = [
  {
    id: 'pos-1',
    title: 'GROUP CHIEF - SUPPLY CHAIN',
    company: 'CAREER141',
    location: 'Colombo, Western Province, Sri Lanka',
    workplaceType: 'On-site',
    recruiterName: 'Azeemusham Ansarideen',
    postedDate: '9/6/2026',
    expiryDays: 25,
    postType: 'Manual',
    projectTitle: 'GROUP CHIEF - SUPPLY CHAIN - LANKA HOSPITALS - THUSHINI',
    status: 'Open',
    viewsCount: 1735,
    applicantsCount: 171,
    newApplicantsCount: 0,
  },
  {
    id: 'pos-2',
    title: 'Data Entry Specialist - Documentation',
    company: 'CAREER141',
    location: 'Colombo, Western Province, Sri Lanka',
    workplaceType: 'On-site',
    recruiterName: 'Azeem Ansar',
    postedDate: '9/1/2026',
    expiryDays: 19,
    postType: 'Manual',
    projectTitle: 'Data Entry',
    status: 'Open',
    viewsCount: 4041,
    applicantsCount: 423,
    newApplicantsCount: 423,
  },
  {
    id: 'pos-3',
    title: 'Graphic Design Intern',
    company: 'CAREER141',
    location: 'Colombo, Western Province, Sri Lanka',
    workplaceType: 'On-site',
    recruiterName: 'Chathura Sampath',
    postedDate: '8/17/2026',
    expiryDays: 4,
    postType: 'Manual',
    projectTitle: 'Career141 - Intern Graphic Designer - Chathura',
    status: 'Open',
    viewsCount: 1007,
    applicantsCount: 66,
    newApplicantsCount: 64,
  },
  {
    id: 'pos-4',
    title: 'DGM – Merchandising',
    company: 'CAREER141',
    location: 'Dhaka, Bangladesh',
    workplaceType: 'On-site',
    recruiterName: 'Azeemusham Ansarideen',
    postedDate: '9/10/2026',
    expiryDays: 29,
    postType: 'Manual',
    projectTitle: 'ANANTA > DGM - Merchandising > Sanduni',
    status: 'Open',
    viewsCount: 680,
    applicantsCount: 88,
    newApplicantsCount: 77,
  },
  {
    id: 'pos-5',
    title: 'TA Support Coordinator',
    company: 'CAREER141',
    location: 'Colombo, Western Province, Sri Lanka',
    workplaceType: 'Hybrid',
    recruiterName: 'Azeemusham Ansarideen',
    postedDate: '9/10/2026',
    expiryDays: 29,
    postType: 'Manual',
    projectTitle: 'Career141 > TA support > Asma',
    status: 'Open',
    viewsCount: 433,
    applicantsCount: 65,
    newApplicantsCount: 50,
  },
  {
    id: 'pos-6',
    title: 'Professor - IT / Computing',
    company: 'CAREER141',
    location: 'Colombo, Western Province, Sri Lanka',
    workplaceType: 'On-site',
    recruiterName: 'Azeemusham Ansarideen',
    postedDate: '9/11/2026',
    expiryDays: 30,
    postType: 'Manual',
    projectTitle: 'IT Academic Division',
    status: 'Open',
    viewsCount: 0,
    applicantsCount: 0,
    newApplicantsCount: 0,
  },
];

export const LOCATION_OPTIONS = [
  { id: 'sri_lanka', label: 'Sri Lanka', count: 13 },
  { id: 'western_province', label: 'Western Province, Sri Lanka', count: 13 },
  { id: 'colombo_district', label: 'Colombo District, Western Province, Sri Lanka', count: 12 },
  { id: 'colombo', label: 'Colombo, Western Province, Sri Lanka', count: 9 },
];

export const WORKPLACE_OPTIONS = [
  { id: 'On-site', label: 'On-site', count: 20 },
  { id: 'Hybrid', label: 'Hybrid', count: 1 },
  { id: 'Remote', label: 'Remote', count: 0 },
];

export const STATUS_OPTIONS = [
  { id: 'Open', label: 'Open', count: 21 },
  { id: 'Draft', label: 'Draft', count: 39 },
  { id: 'Closed', label: 'Closed', count: 2779 },
  { id: 'In review', label: 'In review', count: 0 },
];
