import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const jobs = mutation({
  args: {},
  handler: async (ctx) => {
    const users = await ctx.db.query("users").collect();
    if (users.length === 0) throw new Error("No users to assign jobs to.");
    
    const ta1 = users[0]._id;
    const ta2 = users.length > 1 ? users[1]._id : users[0]._id;
    const dir = users.length > 2 ? users[2]._id : users[0]._id;

    const dummyJobs = [
      {
        title: "Senior Backend Engineer",
        clientName: "FinTech Solutions",
        clientIndustry: "Financial Services",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Developing high-frequency trading APIs.",
        requiredSkills: ["Go", "PostgreSQL", "Kafka"],
        niceToHaveSkills: ["Rust", "Kubernetes"],
        seniorityLevel: "senior_manager",
        experienceMinYears: 6,
        experienceMaxYears: undefined,
        location: "New York, USA",
        salaryMin: 150000,
        salaryMax: 200000,
        salaryCurrency: "USD",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "FIN-BE-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: false,
        esaCheckEnabled: true,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 40,
        scoreWeightExperience: 20,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 70,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "whatsapp",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "database_matches_70_plus",
        agent5CallScript: "technical_prescreen",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: true,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 3,
        slaClientReviewDays: 3,
        slaInterviewDays: 5,
        slaOfferDays: 3,
        headhuntingEnabled: true,
        benchmarkProfileUrl: "https://linkedin.com/in/example-profile"
      },
      {
        title: "Marketing Executive",
        clientName: "RetailCorp",
        clientIndustry: "Retail",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Executing digital marketing campaigns and managing social media.",
        requiredSkills: ["Social Media Marketing", "SEO", "Content Creation"],
        niceToHaveSkills: undefined,
        seniorityLevel: "entry_level",
        experienceMinYears: 1,
        experienceMaxYears: 3,
        location: "London, UK",
        salaryMin: 30000,
        salaryMax: 40000,
        salaryCurrency: "GBP",
        educationLevel: "any",
        languagesRequired: ["English"],
        keyword: "RET-MKT-01",
        status: "active",
        primaryRecruiterId: ta2,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 30,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 50,
        reverseMatchOnPublish: false,
        agent3Enabled: false,
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 4,
        slaOfferDays: 2,
        headhuntingEnabled: false
      },
      {
        title: "Chief Operating Officer",
        clientName: "Global Logistics Ltd",
        clientIndustry: "Logistics",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Overseeing all operational aspects of the global supply chain.",
        requiredSkills: ["Operations Management", "Supply Chain", "Leadership"],
        niceToHaveSkills: ["Six Sigma", "ERP Systems"],
        seniorityLevel: "c_suite",
        experienceMinYears: 15,
        experienceMaxYears: undefined,
        location: "Dubai, UAE",
        salaryMin: undefined,
        salaryMax: undefined,
        salaryCurrency: "AED",
        educationLevel: "master",
        languagesRequired: ["English", "Arabic"],
        keyword: "GL-COO-01",
        status: "on_hold",
        primaryRecruiterId: dir,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: true,
        rejectionLoopAction: "return_to_client_review",
        scoreWeightSkills: 20,
        scoreWeightExperience: 40,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 20,
        scoreWeightLocation: 0,
        minMatchScoreToShow: 85,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: true,
        slaNoNewCvsDays: 10,
        slaTaReviewDays: 3,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 5,
        slaDirectorReviewDays: 3,
        slaEsaDays: 5,
        slaClientReviewDays: 7,
        slaInterviewDays: 14,
        slaOfferDays: 5,
        headhuntingEnabled: true
      },
      {
        title: "Data Scientist",
        clientName: "HealthAI",
        clientIndustry: "Healthcare",
        recruitmentType: "both",
        isConfidential: false,
        jobDescription: "Building predictive models for patient diagnosis.",
        requiredSkills: ["Python", "Machine Learning", "TensorFlow"],
        niceToHaveSkills: ["NLP", "Healthcare Analytics"],
        seniorityLevel: "mid_level",
        experienceMinYears: 3,
        experienceMaxYears: 6,
        location: "Remote",
        salaryMin: 90000,
        salaryMax: 130000,
        salaryCurrency: "USD",
        educationLevel: "bachelor",
        languagesRequired: undefined,
        keyword: "HAI-DS-02",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: dir,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 45,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 15,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 60,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "whatsapp",
        agent3Day4Channel: "email",
        agent3Day7Channel: "sms",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "all_new_applicants",
        agent5CallScript: "technical_prescreen",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: false,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 4,
        slaInterviewDays: 7,
        slaOfferDays: 3,
        headhuntingEnabled: true
      },
      {
        title: "Frontend Developer",
        clientName: "WebSolutions Co",
        clientIndustry: "Information Technology",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Creating beautiful and responsive UIs with React and Tailwind.",
        requiredSkills: ["React", "Tailwind CSS", "JavaScript"],
        niceToHaveSkills: ["Figma", "Next.js"],
        seniorityLevel: "mid_level",
        experienceMinYears: 2,
        experienceMaxYears: 5,
        location: "Berlin, Germany",
        salaryMin: 55000,
        salaryMax: 75000,
        salaryCurrency: "EUR",
        educationLevel: "any",
        languagesRequired: ["German", "English"],
        keyword: "WEB-FE-03",
        status: "filled",
        primaryRecruiterId: ta2,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: false,
        esaCheckEnabled: false,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 40,
        scoreWeightExperience: 20,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 55,
        reverseMatchOnPublish: true,
        agent3Enabled: false,
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 5,
        slaOfferDays: 2,
        headhuntingEnabled: false
      },
      {
        title: "Customer Success Manager",
        clientName: "SaaS Platform Inc",
        clientIndustry: "Software",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Ensuring customer satisfaction, onboarding new clients, and driving renewals.",
        requiredSkills: ["Customer Success", "Account Management", "CRM"],
        niceToHaveSkills: ["Salesforce", "Zendesk"],
        seniorityLevel: "manager",
        experienceMinYears: 4,
        experienceMaxYears: 8,
        location: "Austin, TX, USA",
        salaryMin: 80000,
        salaryMax: 110000,
        salaryCurrency: "USD",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "SAAS-CSM-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 30,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 60,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "whatsapp",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "database_matches_70_plus",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: false,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 3,
        slaInterviewDays: 5,
        slaOfferDays: 3,
        headhuntingEnabled: false
      },
      {
        title: "Director of HR",
        clientName: "ManuCorp",
        clientIndustry: "Manufacturing",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Leading the global HR strategy and talent acquisition efforts.",
        requiredSkills: ["HR Strategy", "Talent Acquisition", "Employee Relations", "Compensation"],
        niceToHaveSkills: undefined,
        seniorityLevel: "director",
        experienceMinYears: 10,
        experienceMaxYears: undefined,
        location: "Chicago, IL, USA",
        salaryMin: 160000,
        salaryMax: 220000,
        salaryCurrency: "USD",
        educationLevel: "master",
        languagesRequired: ["English"],
        keyword: "MANU-HR-DIR",
        status: "active",
        primaryRecruiterId: dir,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: true,
        rejectionLoopAction: "return_to_client_review",
        scoreWeightSkills: 25,
        scoreWeightExperience: 35,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 75,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: true,
        slaNoNewCvsDays: 7,
        slaTaReviewDays: 3,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 3,
        slaDirectorReviewDays: 2,
        slaEsaDays: 5,
        slaClientReviewDays: 5,
        slaInterviewDays: 10,
        slaOfferDays: 4,
        headhuntingEnabled: true
      },
      {
        title: "Product Designer",
        clientName: "Creative AI",
        clientIndustry: "Technology",
        recruitmentType: "both",
        isConfidential: false,
        jobDescription: "Designing user interfaces and experiences for generative AI tools.",
        requiredSkills: ["UI/UX", "Figma", "Prototyping", "User Research"],
        niceToHaveSkills: ["HTML/CSS", "Animation"],
        seniorityLevel: "mid_level",
        experienceMinYears: 3,
        experienceMaxYears: 7,
        location: "Remote - Europe",
        salaryMin: 60000,
        salaryMax: 90000,
        salaryCurrency: "EUR",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "CAI-PD-04",
        status: "draft",
        primaryRecruiterId: ta2,
        directorId: dir,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 40,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 60,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "whatsapp",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "all_new_applicants",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: false,
        slaNoNewCvsDays: 4,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 3,
        slaInterviewDays: 5,
        slaOfferDays: 2,
        headhuntingEnabled: true
      },
      {
        title: "Sales Representative",
        clientName: "FastFMCG",
        clientIndustry: "FMCG",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Field sales and account management for regional grocery chains.",
        requiredSkills: ["B2B Sales", "Negotiation", "Account Management"],
        niceToHaveSkills: ["FMCG Experience"],
        seniorityLevel: "entry_level",
        experienceMinYears: 0,
        experienceMaxYears: 2,
        location: "Manchester, UK",
        salaryMin: 25000,
        salaryMax: 35000,
        salaryCurrency: "GBP",
        educationLevel: "diploma",
        languagesRequired: ["English"],
        keyword: "FMCG-SALES-01",
        status: "cancelled",
        primaryRecruiterId: ta1,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 20,
        scoreWeightExperience: 20,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 20,
        scoreWeightLocation: 20,
        minMatchScoreToShow: 40,
        reverseMatchOnPublish: false,
        agent3Enabled: false,
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 3,
        slaOfferDays: 1,
        headhuntingEnabled: false
      },
      {
        title: "DevOps Engineer",
        clientName: "CloudScale",
        clientIndustry: "IT Services",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Managing cloud infrastructure and CI/CD pipelines.",
        requiredSkills: ["AWS", "Terraform", "Docker", "CI/CD"],
        niceToHaveSkills: ["Python", "Golang"],
        seniorityLevel: "senior_manager",
        experienceMinYears: 5,
        experienceMaxYears: 10,
        location: "Sydney, Australia",
        salaryMin: 120000,
        salaryMax: 160000,
        salaryCurrency: "AUD",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "CS-DEVOPS-01",
        status: "active",
        primaryRecruiterId: dir,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "return_to_client_review",
        scoreWeightSkills: 45,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 15,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 65,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: true,
        agent5Trigger: "database_matches_70_plus",
        agent5CallScript: "technical_prescreen",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: true,
        slaNoNewCvsDays: 7,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 4,
        slaInterviewDays: 7,
        slaOfferDays: 3,
        headhuntingEnabled: true
      },
      {
        title: "Legal Counsel",
        clientName: "Law & Partners",
        clientIndustry: "Legal",
        recruitmentType: "headhunting",
        isConfidential: false,
        jobDescription: "Providing corporate legal advice and contract review.",
        requiredSkills: ["Corporate Law", "Contract Negotiation", "Compliance"],
        niceToHaveSkills: ["Mergers & Acquisitions"],
        seniorityLevel: "manager",
        experienceMinYears: 6,
        experienceMaxYears: 12,
        location: "Toronto, Canada",
        salaryMin: 130000,
        salaryMax: 180000,
        salaryCurrency: "CAD",
        educationLevel: "professional_cert",
        languagesRequired: ["English", "French"],
        keyword: "LP-LEGAL-01",
        status: "active",
        primaryRecruiterId: ta2,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: true,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 30,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 70,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 3,
        slaDirectorReviewDays: 2,
        slaEsaDays: 5,
        slaClientReviewDays: 5,
        slaInterviewDays: 10,
        slaOfferDays: 4,
        headhuntingEnabled: true
      },
      {
        title: "Project Manager",
        clientName: "BuildIt Construction",
        clientIndustry: "Construction",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Managing large-scale commercial construction projects.",
        requiredSkills: ["Project Management", "Budgeting", "Scheduling", "AutoCAD"],
        niceToHaveSkills: ["PMP Certification"],
        seniorityLevel: "manager",
        experienceMinYears: 5,
        experienceMaxYears: 15,
        location: "Singapore",
        salaryMin: 8000,
        salaryMax: 12000,
        salaryCurrency: "SGD",
        educationLevel: "bachelor",
        languagesRequired: ["English", "Mandarin"],
        keyword: "BC-PM-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: dir,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 35,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 60,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "whatsapp",
        agent3Day4Channel: "email",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "all_new_applicants",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: false,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 4,
        slaInterviewDays: 7,
        slaOfferDays: 3,
        headhuntingEnabled: false
      },
      {
        title: "Quality Assurance Analyst",
        clientName: "SoftwareHub",
        clientIndustry: "IT Services",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Manual and automated testing of web applications.",
        requiredSkills: ["Manual Testing", "Selenium", "JIRA", "API Testing"],
        niceToHaveSkills: ["Cypress", "Postman"],
        seniorityLevel: "mid_level",
        experienceMinYears: 2,
        experienceMaxYears: 5,
        location: "Pune, India",
        salaryMin: 500000,
        salaryMax: 800000,
        salaryCurrency: "INR",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "SH-QA-01",
        status: "active",
        primaryRecruiterId: ta2,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: false,
        esaCheckEnabled: false,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 40,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 55,
        reverseMatchOnPublish: false,
        agent3Enabled: false,
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "all_new_applicants",
        agent5CallScript: "technical_prescreen",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 4,
        slaOfferDays: 2,
        headhuntingEnabled: false
      },
      {
        title: "Medical Representative",
        clientName: "PharmaCare",
        clientIndustry: "Pharmaceuticals",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Promoting pharmaceutical products to healthcare professionals.",
        requiredSkills: ["Medical Sales", "Communication", "Relationship Building"],
        niceToHaveSkills: ["Pharmacy Degree"],
        seniorityLevel: "entry_level",
        experienceMinYears: 0,
        experienceMaxYears: 3,
        location: "Cape Town, South Africa",
        salaryMin: 200000,
        salaryMax: 300000,
        salaryCurrency: "ZAR",
        educationLevel: "diploma",
        languagesRequired: ["English", "Afrikaans"],
        keyword: "PC-MR-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 20,
        scoreWeightExperience: 20,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 20,
        scoreWeightLocation: 20,
        minMatchScoreToShow: 40,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "whatsapp",
        agent3Day4Channel: "sms",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 3,
        slaOfferDays: 1,
        headhuntingEnabled: false
      },
      {
        title: "Supply Chain Manager",
        clientName: "EcomGiants",
        clientIndustry: "E-commerce",
        recruitmentType: "both",
        isConfidential: true,
        jobDescription: "Optimizing logistics and inventory management for a major e-commerce platform.",
        requiredSkills: ["Supply Chain Optimization", "Inventory Management", "Logistics"],
        niceToHaveSkills: ["Data Analytics", "PowerBI"],
        seniorityLevel: "manager",
        experienceMinYears: 7,
        experienceMaxYears: 12,
        location: "Tokyo, Japan",
        salaryMin: 8000000,
        salaryMax: 12000000,
        salaryCurrency: "JPY",
        educationLevel: "bachelor",
        languagesRequired: ["Japanese", "English"],
        keyword: "EG-SCM-01",
        status: "filled",
        primaryRecruiterId: ta2,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "return_to_client_review",
        scoreWeightSkills: 30,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 15,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 65,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: true,
        agent5Trigger: "database_matches_70_plus",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: true,
        slaNoNewCvsDays: 5,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 0,
        slaClientReviewDays: 3,
        slaInterviewDays: 5,
        slaOfferDays: 3,
        headhuntingEnabled: true
      },
      {
        title: "UX Researcher",
        clientName: "Design Innovations",
        clientIndustry: "Design",
        recruitmentType: "both",
        isConfidential: false,
        jobDescription: "Conducting user interviews and usability testing for new products.",
        requiredSkills: ["User Research", "Usability Testing", "Data Analysis"],
        niceToHaveSkills: undefined,
        seniorityLevel: "mid_level",
        experienceMinYears: 3,
        experienceMaxYears: 6,
        location: "San Francisco, CA, USA",
        salaryMin: 90000,
        salaryMax: 120000,
        salaryCurrency: "USD",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "DI-UXR-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 35,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 60,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 4,
        slaTaReviewDays: 2,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 3,
        slaInterviewDays: 5,
        slaOfferDays: 2,
        headhuntingEnabled: false
      },
      {
        title: "Investment Banking Analyst",
        clientName: "Alpha Capital",
        clientIndustry: "Finance",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Financial modeling, valuation, and M&A execution.",
        requiredSkills: ["Financial Modeling", "Valuation", "Excel"],
        niceToHaveSkills: ["Bloomberg Terminal"],
        seniorityLevel: "entry_level",
        experienceMinYears: 0,
        experienceMaxYears: 2,
        location: "London, UK",
        salaryMin: 60000,
        salaryMax: 80000,
        salaryCurrency: "GBP",
        educationLevel: "bachelor",
        languagesRequired: ["English"],
        keyword: "AC-IBA-01",
        status: "on_hold",
        primaryRecruiterId: dir,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: true,
        rejectionLoopAction: "ask_ta_each_time",
        scoreWeightSkills: 40,
        scoreWeightExperience: 10,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 20,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 65,
        reverseMatchOnPublish: true,
        agent3Enabled: false,
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: true,
        agent5Trigger: "database_matches_70_plus",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "trigger_agent3",
        agent5HideCompany: true,
        slaNoNewCvsDays: 7,
        slaTaReviewDays: 2,
        slaAiCallDays: 1,
        slaSecondShortlistDays: 2,
        slaDirectorReviewDays: 2,
        slaEsaDays: 3,
        slaClientReviewDays: 4,
        slaInterviewDays: 7,
        slaOfferDays: 2,
        headhuntingEnabled: true
      },
      {
        title: "Chief Technology Officer",
        clientName: "NextGen Startup",
        clientIndustry: "Technology",
        recruitmentType: "headhunting",
        isConfidential: true,
        jobDescription: "Leading the technology vision and engineering team for a high-growth startup.",
        requiredSkills: ["Technology Strategy", "Team Leadership", "System Architecture", "Cloud Native"],
        niceToHaveSkills: ["AI/ML Knowledge", "Fundraising Experience"],
        seniorityLevel: "c_suite",
        experienceMinYears: 12,
        experienceMaxYears: undefined,
        location: "Remote",
        salaryMin: 200000,
        salaryMax: 250000,
        salaryCurrency: "USD",
        educationLevel: "master",
        languagesRequired: ["English"],
        keyword: "NGS-CTO-01",
        status: "active",
        primaryRecruiterId: dir,
        directorId: dir,
        directorReviewEnabled: true,
        clientReviewEnabled: true,
        esaCheckEnabled: true,
        rejectionLoopAction: "return_to_client_review",
        scoreWeightSkills: 30,
        scoreWeightExperience: 30,
        scoreWeightJobTitle: 20,
        scoreWeightIndustry: 15,
        scoreWeightLocation: 5,
        minMatchScoreToShow: 80,
        reverseMatchOnPublish: true,
        agent3Enabled: true,
        agent3Day2Channel: "email",
        agent3Day4Channel: "email",
        agent3Day7Channel: "email",
        agent3AfterDay7: "continue_weekly",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "initial_screening",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: true,
        slaNoNewCvsDays: 14,
        slaTaReviewDays: 3,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 4,
        slaDirectorReviewDays: 3,
        slaEsaDays: 5,
        slaClientReviewDays: 7,
        slaInterviewDays: 14,
        slaOfferDays: 5,
        headhuntingEnabled: true
      },
      {
        title: "Social Media Manager",
        clientName: "Trendy Brands",
        clientIndustry: "Marketing",
        recruitmentType: "job_posting",
        isConfidential: false,
        jobDescription: "Managing social media presence across Instagram, TikTok, and Twitter.",
        requiredSkills: ["Social Media Management", "Content Strategy", "Analytics"],
        niceToHaveSkills: ["Video Editing", "Graphic Design"],
        seniorityLevel: "manager",
        experienceMinYears: 3,
        experienceMaxYears: 6,
        location: "Los Angeles, CA, USA",
        salaryMin: 70000,
        salaryMax: 90000,
        salaryCurrency: "USD",
        educationLevel: "any",
        languagesRequired: ["English", "Spanish"],
        keyword: "TB-SMM-01",
        status: "active",
        primaryRecruiterId: ta1,
        directorId: undefined,
        directorReviewEnabled: false,
        clientReviewEnabled: true,
        esaCheckEnabled: false,
        rejectionLoopAction: "restart_from_new_cvs",
        scoreWeightSkills: 40,
        scoreWeightExperience: 25,
        scoreWeightJobTitle: 15,
        scoreWeightIndustry: 10,
        scoreWeightLocation: 10,
        minMatchScoreToShow: 55,
        reverseMatchOnPublish: false,
        agent3Enabled: true,
        agent3Day2Channel: "whatsapp",
        agent3Day4Channel: "email",
        agent3Day7Channel: "whatsapp",
        agent3AfterDay7: "mark_unresponsive",
        agent5Enabled: false,
        agent5Trigger: "manual_only",
        agent5CallScript: "default",
        agent5NoAnswerAction: "notify_ta",
        agent5HideCompany: false,
        slaNoNewCvsDays: 3,
        slaTaReviewDays: 1,
        slaAiCallDays: 0,
        slaSecondShortlistDays: 1,
        slaDirectorReviewDays: 0,
        slaEsaDays: 0,
        slaClientReviewDays: 2,
        slaInterviewDays: 5,
        slaOfferDays: 2,
        headhuntingEnabled: false
      }
    ];

    for (const job of dummyJobs) {
      const now = new Date().toISOString();
      await ctx.db.insert("jobs", { ...job, createdAt: now, updatedAt: now } as any);
    }
  }
});
