import {
  MockCandidate,
  LinkedInJobPost,
  DatabaseCvItem,
  ReferenceCheckItem,
  MessageSnippet,
  PipelineSubStage,
} from './types';

export const PIPELINE_SUB_STAGES: PipelineSubStage[] = [
  { id: 'follow_up', label: 'Follow - up' },
  { id: 'director_review', label: 'Director Review' },
  { id: 'director_shortlist', label: 'Director shortlist' },
  { id: 'client_shortlist', label: 'Client shortlist' },
  { id: 'interview', label: 'Interview' },
  { id: 'offer', label: 'Offer' },
];

const createStageCandidates = (stageKey: MockCandidate['stage'], prefix: string): MockCandidate[] => [
  {
    id: `${prefix}-1`,
    name: 'Nethma Tharindi',
    degreeRank: '2nd',
    isApplicant: true,
    role: 'HR Associate',
    location: 'Colombo, Western Province, Sri Lanka',
    industry: 'Food and Beverage Manufacturing',
    experiences: [
      {
        title: 'Human Resources Associate',
        company: 'Outdesk.',
        period: '2025 – Present',
      },
      {
        title: 'Human Resources Intern',
        company: 'Outdesk.',
        period: '2025 – 2025',
      },
    ],
    educations: [
      {
        institution: 'University of Colombo',
        degree: 'Bachelor of Business Administration - BBA',
        period: '2022 – 2026',
      },
      {
        institution: 'AAT Sri Lanka',
        degree: '',
        period: '2022',
      },
      {
        institution: 'Institute of Certified Management Accountants of Sri Lanka (CMA)',
        degree: '',
        period: '2023',
      },
    ],
    moreEducationsCount: 5,
    highlight: 'This candidate is connected to 1 employee at your company',
    skillsMatch: {
      matched: 2,
      total: 10,
      tags: ['Attention to Detail', 'Communication'],
    },
    interest: '19 connections',
    activity: 'resume · In 2 projects · 2 views · Applied to 2 jobs',
    savedBy: 'Nipuni Senanayake',
    savedDate: 'March 23, 2025',
    currentSalary: 'LKR 120,000 / mo',
    expectedSalary: 'LKR 160,000 / mo',
    noticePeriod: '1 Month',
    email: 'ashvinvgithimal@gmail.com',
    phone: '+94712798490',
    headline:
      'Business Development Manager - Maldives and 1st World Countries | Driving global growth in premium beverages',
    companySummary:
      'Lion Brewery (Ceylon) PLC · Cardiff Metropolitan University · Sri Lanka · 500+',
    projectContext: 'DELMO - General Manager - Sales - THUSHINI',
    cvFileName: 'Nethma Tharindi - CV.pdf',
    cvUploadedDate: 'March 10, 2026',
    stage: stageKey,
    stageStatus: 'In contacted',
    stageChangedDate: 'April 28, 2025',
    stageChangedBy: 'Nipuni Senanayake',
    fitScore: 82,
  },
  {
    id: `${prefix}-2`,
    name: 'Kavindu Perera',
    degreeRank: '1st',
    isApplicant: true,
    role: 'Senior Talent Acquisition Specialist',
    location: 'Colombo, Western Province, Sri Lanka',
    industry: 'Information Technology and Services',
    experiences: [
      {
        title: 'Senior Talent Acquisition Specialist',
        company: 'Virtusa',
        period: '2023 – Present',
      },
      {
        title: 'Technical Recruiter',
        company: 'Sysco LABS Sri Lanka',
        period: '2021 – 2023',
      },
    ],
    educations: [
      {
        institution: 'University of Kelaniya',
        degree: 'B.Sc. in Human Resource Management',
        period: '2017 – 2021',
      },
      {
        institution: 'CIPM Sri Lanka',
        degree: 'Chartered Qualification in HRM (CQHRM)',
        period: '2020',
      },
    ],
    moreEducationsCount: 3,
    highlight: 'Candidate has 4+ years of relevant tech recruitment experience',
    skillsMatch: {
      matched: 4,
      total: 10,
      tags: ['Technical Recruiting', 'Candidate Sourcing', 'Interviewing', 'Communication'],
    },
    interest: '42 connections',
    activity: 'resume · In 3 projects · 5 views · Applied to 1 job',
    savedBy: 'Nipuni Senanayake',
    savedDate: 'March 20, 2025',
    currentSalary: 'LKR 210,000 / mo',
    expectedSalary: 'LKR 280,000 / mo',
    noticePeriod: 'Immediate (2 weeks)',
    email: 'kavindu.recruiter@gmail.com',
    phone: '+94771234567',
    headline:
      'Senior Talent Acquisition Specialist | Tech Recruitment & Talent Sourcing Leader',
    companySummary:
      'Virtusa · University of Kelaniya · Sri Lanka · 500+',
    projectContext: 'DELMO - General Manager - Sales - THUSHINI',
    cvFileName: 'Kavindu Perera - CV.pdf',
    cvUploadedDate: 'March 10, 2026',
    stage: stageKey,
    stageStatus: 'In contacted',
    stageChangedDate: 'April 27, 2025',
    stageChangedBy: 'Nipuni Senanayake',
    fitScore: 91,
  },
];

const REFERENCE_CANDIDATES: MockCandidate[] = [
  {
    id: 'cand-ref-1',
    name: 'Nethma Tharindi',
    degreeRank: '2nd',
    isApplicant: true,
    role: 'HR Associate',
    location: 'Colombo, Western Province, Sri Lanka',
    industry: 'Food and Beverage Manufacturing',
    experiences: [
      {
        title: 'Human Resources Associate',
        company: 'Outdesk.',
        period: '2025 – Present',
      },
      {
        title: 'Human Resources Intern',
        company: 'Outdesk.',
        period: '2025 – 2025',
      },
    ],
    educations: [
      {
        institution: 'University of Colombo',
        degree: 'Bachelor of Business Administration - BBA',
        period: '2022 – 2026',
      },
      {
        institution: 'AAT Sri Lanka',
        degree: '',
        period: '2022',
      },
      {
        institution: 'Institute of Certified Management Accountants of Sri Lanka (CMA)',
        degree: '',
        period: '2023',
      },
    ],
    moreEducationsCount: 5,
    highlight: 'This candidate is connected to 1 employee at your company',
    skillsMatch: {
      matched: 2,
      total: 10,
      tags: ['Attention to Detail', 'Communication'],
    },
    interest: '19 connections',
    activity: 'resume · In 2 projects · 2 views · Applied to 2 jobs',
    savedBy: 'Nipuni Senanayake',
    savedDate: 'March 23, 2025',
    currentSalary: 'LKR 120,000 / mo',
    expectedSalary: 'LKR 160,000 / mo',
    noticePeriod: '1 Month',
    email: 'nethma.tharindi@outdesk.com',
    emails: ['nethma.tharindi@outdesk.com', 'nethma.tharindi.personal@gmail.com'],
    phone: '+94 71 279 8490',
    phoneNumbers: ['+94 71 279 8490', '+94 11 289 4521'],
    designations: ['Human Resources Associate at Outdesk.'],
    locations: ['Colombo, Western Province, Sri Lanka'],
    headline:
      'Business Development Manager - Maldives and 1st World Countries | Driving global growth in premium beverages',
    companySummary:
      'Lion Brewery (Ceylon) PLC · Cardiff Metropolitan University · Sri Lanka · 500+',
    projectContext: 'DELMO - General Manager - Sales - THUSHINI',
    cvFileName: 'Nethma Tharindi - CV.pdf',
    cvUploadedDate: 'March 10, 2026',
    stage: 'reference',
    stageStatus: 'In contacted',
    stageChangedDate: 'April 28, 2025',
    stageChangedBy: 'Nipuni Senanayake',
    fitScore: 82,
  },
];

export const INITIAL_CANDIDATES: MockCandidate[] = [
  ...createStageCandidates('follow_up', 'cand-fu'),
  ...createStageCandidates('director_review', 'cand-dr'),
  ...createStageCandidates('director_shortlist', 'cand-ds'),
  ...createStageCandidates('client_shortlist', 'cand-cs'),
  ...createStageCandidates('interview', 'cand-iv'),
  ...createStageCandidates('offer', 'cand-of'),
  ...createStageCandidates('linkedin_job', 'cand-lj'),
  ...createStageCandidates('database_cv', 'cand-db'),
  ...REFERENCE_CANDIDATES,
];

export const LINKEDIN_JOBS_MOCK: LinkedInJobPost[] = [
  {
    id: 'job-1',
    title: 'Senior Talent Acquisition Specialist',
    company: 'Career141 Client — Tech Division',
    location: 'Colombo, Sri Lanka (Hybrid)',
    workplaceType: 'Hybrid',
    postedDate: '6 days ago',
    applicantsCount: 54,
    inReviewCount: 12,
    sourcedCount: 18,
    status: 'Active',
    hiringManager: 'Binath Fernando',
  },
  {
    id: 'job-2',
    title: 'Lead Fullstack Engineer (Next.js & Node)',
    company: 'Fintech Innovations Ltd',
    location: 'Colombo, Sri Lanka (Remote)',
    workplaceType: 'Remote',
    postedDate: '2 weeks ago',
    applicantsCount: 78,
    inReviewCount: 8,
    sourcedCount: 22,
    status: 'Active',
    hiringManager: 'Nipuni Senanayake',
  },
  {
    id: 'job-3',
    title: 'DevOps & Site Reliability Architect',
    company: 'Global Cloud Solutions',
    location: 'Colombo / Kandy, Sri Lanka',
    workplaceType: 'Hybrid',
    postedDate: '3 weeks ago',
    applicantsCount: 36,
    inReviewCount: 5,
    sourcedCount: 14,
    status: 'Active',
    hiringManager: 'Binath Fernando',
  },
];

export const DATABASE_CVS_MOCK: DatabaseCvItem[] = [
  {
    id: 'db-1',
    name: 'Anuki Jayasuriya',
    role: 'HR Operations Manager',
    experienceYears: 6,
    currentCompany: 'MAS Holdings',
    location: 'Colombo, Sri Lanka',
    source: 'WhatsApp',
    parsedDate: 'May 3, 2025',
    topSkills: ['HR Operations', 'Workday', 'Compensation & Benefits', 'Labor Law'],
    isInPipeline: false,
  },
  {
    id: 'db-2',
    name: 'Tharindu Wickramatunga',
    role: 'Senior React / Node Developer',
    experienceYears: 5,
    currentCompany: 'IFS World',
    location: 'Colombo, Sri Lanka',
    source: 'LinkedIn',
    parsedDate: 'May 2, 2025',
    topSkills: ['React', 'TypeScript', 'TailwindCSS', 'GraphQL', 'Jest'],
    isInPipeline: false,
  },
  {
    id: 'db-3',
    name: 'Rumesh Madushanka',
    role: 'Cloud Security Engineer',
    experienceYears: 4,
    currentCompany: 'Dialog Axiata',
    location: 'Colombo, Sri Lanka',
    source: 'Email',
    parsedDate: 'April 30, 2025',
    topSkills: ['AWS Security', 'SOC2', 'Firewalls', 'SIEM', 'Penetration Testing'],
    isInPipeline: true,
  },
  {
    id: 'db-4',
    name: 'Sanduni Rajapaksa',
    role: 'Talent Sourcing Specialist',
    experienceYears: 3,
    currentCompany: 'Brandix',
    location: 'Colombo, Sri Lanka',
    source: 'WhatsApp',
    parsedDate: 'April 28, 2025',
    topSkills: ['Boolean Search', 'LinkedIn Recruiter', 'Headhunting', 'Screening'],
    isInPipeline: false,
  },
  {
    id: 'db-5',
    name: 'Kasun Abeyratne',
    role: 'Senior QA Engineer (Automation)',
    experienceYears: 7,
    currentCompany: 'Fortude',
    location: 'Colombo, Sri Lanka',
    source: 'Bulk Upload',
    parsedDate: 'April 25, 2025',
    topSkills: ['Selenium', 'Java', 'Postman', 'TestRail', 'Performance Testing'],
    isInPipeline: true,
  },
  {
    id: 'db-6',
    name: 'Minoli Ratnayake',
    role: 'Finance & Accounting Specialist',
    experienceYears: 4,
    currentCompany: 'KPMG Sri Lanka',
    location: 'Colombo, Sri Lanka',
    source: 'Email',
    parsedDate: 'April 22, 2025',
    topSkills: ['Financial Auditing', 'ACCA', 'Tax Compliance', 'SAP ERP'],
    isInPipeline: false,
  },
];

export const REFERENCE_CHECKS_MOCK: ReferenceCheckItem[] = [
  {
    id: 'ref-1',
    candidateName: 'Shenali Perera',
    role: 'Senior Financial Analyst',
    refereeName: 'Dinesh Wickramasinghe',
    refereeTitle: 'VP Finance & Strategy',
    refereeCompany: 'John Keells Holdings',
    status: 'Verified',
    verifiedDate: 'May 3, 2025',
    rating: 5,
    notes: 'Exceptional financial modeling and diligence. Highly recommended with no reservations.',
  },
  {
    id: 'ref-2',
    candidateName: 'Hasitha Senaratne',
    role: 'QA Automation Lead',
    refereeName: 'Suraj Gunawardena',
    refereeTitle: 'Head of Quality Engineering',
    refereeCompany: 'Axiata Digital Labs',
    status: 'Verified',
    verifiedDate: 'May 2, 2025',
    rating: 5,
    notes: 'Strong technical leader who established automated CI/CD testing framework. Very reliable.',
  },
  {
    id: 'ref-3',
    candidateName: 'Sachithra Weerasinghe',
    role: 'Senior UI/UX Designer',
    refereeName: 'Amila Fernando',
    refereeTitle: 'Creative Director',
    refereeCompany: 'Creative Software',
    status: 'In Progress',
    rating: 4,
    notes: 'Call scheduled with referee for Monday 10:00 AM IST to confirm design leadership tenure.',
  },
  {
    id: 'ref-4',
    candidateName: 'Dilshan Wickramasinghe',
    role: 'Lead Fullstack Developer',
    refereeName: 'Prashan Rodrigo',
    refereeTitle: 'Engineering Manager',
    refereeCompany: 'LSEG Technology',
    status: 'Pending Contact',
    rating: 0,
    notes: 'Outreach email sent to corporate address. Awaiting referee confirmation.',
  },
];

export const SNIPPETS_MOCK: MessageSnippet[] = [
  {
    id: 'snip-1',
    title: 'Salary & Notice Period Missing Details Inquiry',
    category: 'Follow-up',
    subject: 'Update regarding your application with Career141',
    body: `Hi {candidate_name},\n\nThank you for sharing your profile with us! To help us fast-track your profile for client review, could you please confirm:\n1. Your current gross salary (monthly)\n2. Your expected gross salary (monthly)\n3. Your official notice period / earliest availability\n\nLooking forward to hearing from you!`,
    lastUsed: 'Yesterday',
  },
  {
    id: 'snip-2',
    title: 'Director Shortlist Notification & Profile Pitch',
    category: 'Director Shortlist',
    subject: 'Exciting Career Opportunity - Executive Shortlist',
    body: `Hi {candidate_name},\n\nGreat news! Our recruitment leadership team has reviewed your profile and shortlisted you for our {job_title} role. We would love to introduce your candidacy to the hiring director.\n\nPlease let us know if your resume is up-to-date and if you are open for a confidential chat this week.`,
    lastUsed: '2 days ago',
  },
  {
    id: 'snip-3',
    title: 'Technical & Culture Interview Invitation',
    category: 'Interview',
    subject: 'Interview Invitation for {job_title} at Career141 Client',
    body: `Hi {candidate_name},\n\nThe client interview panel was very impressed with your background and has requested a 45-minute technical conversation. Please choose a suitable slot via our recruitment calendar: {calendar_link}.\n\nBest regards,\nCareer141 Talent Acquisition Team`,
    lastUsed: 'May 4, 2025',
  },
  {
    id: 'snip-4',
    title: 'Formal Offer Letter Follow-up & Discussion',
    category: 'Offer',
    subject: 'Congratulations! Official Offer for {job_title}',
    body: `Hi {candidate_name},\n\nOn behalf of the hiring board, we are thrilled to extend a formal offer of employment for the position of {job_title}.\n\nPlease review the attached offer letter and compensation schedule. We are available for a brief call to answer any questions regarding onboarding!`,
    lastUsed: 'May 3, 2025',
  },
  {
    id: 'snip-5',
    title: 'Polite Rejection & Talent Pool Retention',
    category: 'General',
    subject: 'Update on your application for {job_title}',
    body: `Hi {candidate_name},\n\nThank you for taking the time to discuss your experience with us. While we have chosen to proceed with another profile for this particular vacancy, we were very impressed by your background and will retain your CV in our active talent pool for upcoming openings.`,
    lastUsed: 'April 30, 2025',
  },
];
